version: '3.2'

services:
  mysqldb:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: PizzeriaHead
      MYSQL_USER : utente
      MYSQL_PASSWORD: utente   

  
  pizzeria:
    build:
      context: .
      dockerfile: app.Dockerfile
    depends_on:
      - mysqldb
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/PizzeriaHead
      SPRING_DATASOURCE_USERNAME: utente
      SPRING_DATASOURCE_PASSWORD: utente
    restart:
        always